spring.datasource.url=jdbc:postgresql://localhost:5432/yourticket
spring.datasource.username=postgres
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

spring.data.redis.host=localhost
spring.data.redis.port=6379

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=yourticket-group
spring.kafka.consumer.auto-offset-reset=earliest